
  export const productsArr = [
    {
      id: '1',
      title: 'Premium Wireless Headphones',
      category: 'electronics',
      price: 2999,
      image: '/assets/images/temp/headphones-1.jpg',
      height: 280,
    },
    {
      id: '2',
      title: 'Elegant Red Saree',
      category: 'ethnic-wear',
      price: 4500,
      image: '/assets/images/temp/ethnic-1.jpg',
      height: 460,
    },
    {
      id: '3',
      title: 'Bluetooth Speaker',
      category: 'electronics',
      price: 1999,
      image: '/assets/images/temp/speaker-1.jpg',
      height: 220,
    },
    {
      id: '4',
      title: 'Designer Lehenga Choli',
      category: 'ethnic-wear',
      price: 8999,
      image: '/assets/images/temp/ethnic-2.jpg',
      height: 520,
    },
    {
      id: '5',
      title: 'Studio Headphones',
      category: 'electronics',
      price: 3499,
      image: '/assets/images/temp/headphones-2.jpg',
      height: 340,
    },
    {
      id: '6',
      title: 'Sweatshirt jacket',
      category: 'ethnic-wear',
      price: 2499,
      image: '/assets/images/temp/ethnic-3.jpg',
      height: 400,
    },
    {
      id: '7',
      title: 'Portable Speaker',
      category: 'electronics',
      price: 1499,
      image: '/assets/images/temp/speaker-2.jpg',
      height: 240,
    },
    {
      id: '8',
      title: 'Embroidered Anarkali',
      category: 'ethnic-wear',
      price: 5999,
      image: '/assets/images/temp/ethnic-4.jpg',
      height: 480,
    },
    {
      id: '9',
      title: 'Wireless Earbuds',
      category: 'electronics',
      price: 2499,
      image: '/assets/images/temp/headphones-3.jpg',
      height: 260,
    },
    {
      id: '10',
      title: 'Premium Speaker System',
      category: 'electronics',
      price: 4999,
      image: '/assets/images/temp/speaker-3.jpg',
      height: 300,
    },
    {
      id: '11',
      title: 'Festive Saree Collection',
      category: 'ethnic-wear',
      price: 6500,
      image: '/assets/images/temp/ethnic-5.jpg',
      height: 440,
    },
  ];
  